### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by akimurase** [akimurase/furima_29385#11]
自身のフリマアプリのURL
https://furima-29385.herokuapp.com/

Basic認証のIDとパスワード
admin
3333

出品者用のメールアドレスとパスワード
test@co.jp
test123

購入者用のメールアドレスとパスワード
btest@co.jp
test123

購入用カードの番号・期限・セキュリティコード
4242424242424242
登録時より未来
123

**Comment by yoshim0115** [comment]
村瀬さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品詳細画面にて「商品名」「商品説明」が反映されていないので修正お願いします。（画像1枚目）
・購入ボタンを押すと以下のエラー文が表示されてしまうので修正お願いします。（画像2枚目）
<img width="819" alt="スクリーンショット 2020-09-21 17 09 57" src="https://user-images.githubusercontent.com/57244739/93835892-bd1b7a80-fcbb-11ea-9f94-1ae539e96574.png">
<img width="568" alt="スクリーンショット 2020-08-10 10 32 08" src="https://user-images.githubusercontent.com/57244739/93835899-c3a9f200-fcbb-11ea-806d-7640bf9c5980.png">


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by akimurase** [comment]
挙動確認ありがとうございます！

[修正箇所]
私の方では上記のエラーは確認できず想定通り挙動になってます。
再度チェックしていただけないでしょうか？

**Comment by akimurase** [comment]
指摘箇所修正しております。
ご確認よろしくお願いします！

**Comment by yoshim0115** [comment]
村瀬さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品名の修正ありがとうございます。ですが、商品説明の表示が商品名になって表示されてしまっているので修正お願いします！なお編集ページにて「商品の説明」の文章を変えても変更されませんでした。
<img width="434" alt="スクリーンショット 2020-09-22 12 21 41" src="https://user-images.githubusercontent.com/57244739/93841383-610e2180-fcce-11ea-8ae6-8d0b9d46308f.png">

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by akimurase** [comment]
指摘箇所修正しております。
ご確認よろしくお願いします！

**Comment by yoshim0115** [comment]
村瀬さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

なおこちら挙動確認チェックリストにはありませんが、購入済みの商品詳細ページにて商品IDの後に、商品購入ページへ遷移するURLを直接入力すると、再度商品購入ページへ遷移できる状態です。
（以下の購入済みURLを使用）
https://furima-29385.herokuapp.com/items/91/ordersaddresses

できれば購入済みのページが表示されないように、リダイレクト処理を施しておきましょう。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
